services:
  homeassistant:
    image: linuxserver/homeassistant
    container_name: homeassistant
    hostname: homeassistant
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    restart: unless-stopped
    privileged: true
    networks:
      net:
        ipv4_address: ${APP_IP}
    dns:
      - ${DNS_IP_1}
      - ${DNS_IP_2:-9.9.9.9}

volumes:
  config:
    name: homeassistant-config

networks:
  net:
    external: true
    name: webapps-network